- hosts: ubuntu
  become: yes
  roles:
    - ecrc-access-restriction

- hosts: ecrc
  become: yes
  roles:
    - devel
    - ecrc-utils
    - user-data-backup
    - collectd-node
    - ecrc-motd

- hosts: intel, amd
  become: yes

  roles:
    - env-modules
