- hosts: ubuntu
  become: yes
  roles:
    - ecrc-access-restriction

- hosts: ecrc, p100
  become: yes
  roles:
    - devel
    - ecrc-utils
    - user-data-backup
    - collectd-node
    - ecrc-motd

- hosts: intel, amd, p100
  become: yes
  roles:
    - env-modules
